### ISSUE TITLE
image_id issue - can't open/read file

### ISSUE THREAD

**Issue by HripsimeS** [mhiyer/coco-annotations-to-xml#4] opened 2023-01-31 11:18 UTC
@mhiyer Hello. I have a dataset annotated with coco json format, but I need to convert it to xml PascalVOC format. I tried to use your script to convert json to xml annotations, but I am getting the following error.

**[ WARN:0@0.681] global loadsave.cpp:244 cv::findDecoder imread_('C:/User/dataset/subset-1/000000009526.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
File "coco_get_annotations_xml_format.py", line 130, in <module>
write_to_xml(image_name, image_dict, image_folder, savepath)
File "coco_get_annotations_xml_format.py", line 33, in write_to_xml
h,w,d = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'**

Then I noticed that in coco dataset the name of images are like numerical **000000009526.jpg** and I understood that **'{0:012d}.jpg'.format(image_id)** part was written for particularly for coco dataset. 

My image's names are **362356,7729.jpg** or **15645644.565.jpg**. How I should modify the script so it just makes a match with **image_id.jpg** image in json file annotations and convert/save it as **image_id.xml** ? Look forward to hearing from you!

**Comment by mhiyer** [comment] 2023-02-03 05:17
Hi @HripsimeS, this code is written keeping the coco dataset in mind. If yours is a custom dataset, I suggest changing how the annotations are read. You can consider changing line 114: image_name = '{0:012d}.jpg'.format(image_id)   to reflect your dataset's format. Since the issue is related to a custom dataset and not to the original coco dataset, I will close it. Thank you.

**Closed as completed by mhiyer** 2023-02-03 05:17 UTC
